[config]
default_to_workspace = false
additional_profiles = ["debug"]


[tasks.choose-profile.env]
MODE = "release"
ADDITIONAL = "--release"

    [tasks.choose-profile.env.debug]
    MODE = "debug"
    ADDITIONAL = "--profile=dev"


[tasks.fmt-check]
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--check"]

[tasks.fmt]
toolchain = "nightly"
command = "cargo"
args = ["fmt"]

[tasks.clippy]
toolchain = "stable"
command = "cargo"
args = ["clippy", "--all-targets", "--", "-D", "warnings"]

[tasks.lint]
run_task = [
    { name = ["clippy"] },
]
dependencies = ["fmt-check"]

[tasks.lint-test]
toolchain = "stable"
command = "cargo"
args = ["test"]
dependencies = ["lint"]
